# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b8ad8fd92a5548af95eb5e4ee15ee4bc37606d0696ca8f0813e8172c3e58fbe486f2d9521f8d4a6ede93142ec5877701c17f9d0d0d2edb3d140debe76db59dc

test:
  secret_key_base: 8ebedd6427abb357f3ded9feb047d78cddc8db8eb2012e872d26d918bfcfbf1783e66856e1d035ae17d718b4f2cb2923bdb1c64b5d49589166fd9f02d44d81e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7b8ad8fd92a5548af95eb5e4ee15ee4bc37606d0696ca8f0813e8172c3e58fbe486f2d9521f8d4a6ede93142ec5877701c17f9d0d0d2edb3d140debe733359dc
